### ISSUE TITLE
Delay between input and output

### ISSUE THREAD

**Issue by rickpowell1311** [drssoccer55/RLBot#16]
Hi guys,

First of all, great work with this - I'm having great fun playing around with it.

I'm having one major problem at the moment though, which is the feedback loop of input from cheat engine and sending the controls back to the game takes too long to process. At first I thought this might be because of the processing I'm doing in between, but actually the AlwaysTowardsTheBall agent demonstrates this by the way it snakes quite a lot to correct itself from this delay.

My suspicion is that the delay is on receiving the input values from cheat engine, rather than sending the control inputs back. When I've debugged the code, the input parameters are saying I'm facing the ball, whereas what I'm seeing is that the car has already turned passed it.

Do you guys experience this? And if so, do you have any tips for trying to solve this?

Thanks,

Rick

**Comment by tarehart** [comment]
When you change the steering input instantly from one direction to the other, I believe the in-game wheels have their motion smoothed out so that they don't reach the new orientation instantly. I've always assumed that was the reason for the snaking. Is the snaking that you see on par with this? https://www.youtube.com/watch?v=muReW_jawvI

We could probably measure round-trip latency more reliably by programming a bot to jump as soon as the ball is moved from the kickoff position, and analyzing a replay or screen recording. I haven't bothered to measure yet, but I might try it this evening.

**Comment by rickpowell1311** [comment]
OK cool - let me know if you get round to it. If not, I'll try something like that myself.

**Comment by drssoccer55** [comment]
Here's an overview of how things work and where possible delays might be currently within RLBot.

- The dll that gets injected into the game has a pretty basic purpose. It starts by allocating [named shared memory](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366551(v=vs.85).aspx). It hooks into the game and after every game tick it writes all the game values to that allocated memory.  It doesn't matter where the dll is injected from.  It could be cheat engine it could be something else it just needs to be injected.  Writing to this memory should be very efficient since it is just writing to RAM.

- Python reads from this same memory.  Again just reading from RAM so this should be pretty quick.  There is a single process which does the reading from memory.  This process does separate reads for each agent and for the display in that order.  It sleeps for 5ms and repeats.  It will not update the inputs if the dll is writing to memory.  It will also not update inputs for an agent if the agent is currently processing.

- Both agents have their own process.  Data is shared between the memory process and the agent processes through the Python [multiprocessing.Value](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Value) which is just a shared memory map on the backend.  An agent process will run an agent to get an output vector, put it on a queue of max size 1 (if it fails the put the exception is caught and continues), and than sleeps 10 ms and repeats.

- The main process checks if there is a value in the queue and if so it will update the vjoy controller.  This process also refreshes the display.  This process sleeps 10ms before repeating.

Sleep values can be tweaked and it will be more responsive.  I found that if I put it too low though my recording gets choppy because of (probably) the high cpu usage.  I am also not sure the delay of the external things like vjoy and direct input and rocket league itself.

**Comment by rickpowell1311** [comment]
Thanks for looking into this - it's obviously my misunderstanding of the game mechanics, particularly with the smoothing of the turn directions, rather than any delayed round trip.

The delays times that you measured above are pretty negligible to what I was expecting to see, so I'm happy that this is not an issue and I'll close
