### ISSUE TITLE
Setting up the development environment

### ISSUE THREAD

**Issue by ddthj** [drssoccer55/RLBot#2]
See [https://github.com/drssoccer55/RLBot/wiki/Setup-Instructions]()

Install python 3.x (tested in 3.5.2 and 3.5.3) 64 bit
Download this repository
[Download pyvjoy](https://github.com/tidzo/pyvjoy), put the repo file in your Python/Lib/site-packages
[Download and install the latest version of VJoy ]
(https://sourceforge.net/projects/vjoystick/files/latest/download)
Copy "vJoyInterface.dll" from your vjoy install folder into the pyvjoy folder
[Install x360ce, 32bit](https://gamerinfo.net/game/rocket-league/x360ce/)
Run "configreVjoy" and make sure 2 devices are green, if not, switch to tab 2 and add it as a new device
Run vJoyList if you want to check the previous step, 2 rows should be active and by running p2join (or any of the p2 button presses) you should see a row 2 turn red on the vJoyList
Run x360 as administrator from the rocketleague binary directory, make sure 2 controllers are active
Run Rocket League (window mode is useful if you want to switch to that)
Create an exhibition match
On the team select screen, run p2join.py (or p2start + p2 press a) and tab back into the game to get into split screen/have a car join in
join the opposite team as yourself, but pause during the countdown to match start
Run runner.py and tab back into the game
Unpause

**Comment by TheBlocks** [comment]
I had some trouble with "OSError: exception: access violation writing 0x00000002" but I managed to solve it.
Just in case anyone else runs into this error, here's what I did to fix it:
* Install _Python 3.6.2 64-bit_ (important that it's not 32-bit)
* Download the _x360ce 32-bit_ and place it in the Rocket League executable directory (`...\steamapps\common\rocketleague\Binaries\Win32`)
* Install _vJoy_ and _pyvjoy_
* Drag `vJoyInterface.dll` found in the _x64_ folder (`...\vJoy\x64\vJoyInterface.dll`) to the pyvjoy (`...\Lib\pyvjoy`) folder
* Add another tab in the `vJoyConfig.exe` (`...\vJoy\x64\vJoyConfig.exe`) so that there's 2 vJoy devices

**Comment by drssoccer55** [comment]
Closing for v3.
