### ISSUE TITLE
Separate air yaw and air roll output

### ISSUE THREAD

**Issue by bmwaterhouse** [drssoccer55/RLBot#21]
For full aerial control, ideally we'd have a separate analog output for both air yaw and air roll. This isn't possible using the default controls (would have to use right stick) so maybe this isn't feasible unless we switch to a direct input method instead of a virtual controller.

Suggested by u/ChalkboardCowboy
https://www.reddit.com/r/RocketLeagueBots/comments/6vu1tr/how_to_create_a_rocket_league_bot_part_1/dnwsdwa/

(Silly Sausage)

**Comment by drssoccer55** [comment]
It's possible to use right stick.  The virtual controller is translated to direct input.  I just didn't want people moving the camera wildly.

I do agree that the default controller scheme is limiting because it doesn't let you do both simultaneously.  I was too much of a casual player to know that this is changeable :p and you just revealed that to me now.  Modifying the framework to a new controller scheme would not be that difficult.

Couple questions / things:
1. What happens to the camera when you use right stick on the ground and in the air with the remapped controls?
2. Changing the controller scheme on player 2 without a physical controller would be painful and hard for keyboard only players to remap.  (They could do it with the virtual controller but it would be a pain to meticulously write out a script to change the controls)
3. If we make controller schemes configurable in RLBot, it would still be obnoxious for a person to have to remap controllers to play bots with different controller schemes.  Essentially tournaments would need to force a certain controller scheme.

I think the ideal thing would be if Rocket League has a generic internal controller state which doesn't prevent you from doing anything simultaneously which we can modify.  That's the direction I would ideally like to go.

**Comment by bmwaterhouse** [comment]
1. You'd need to unmap the camera swivel left/right controls to use the right stick for air roll without the camera swiveling all over the place.
2. Yep. I had to disconnect the vJoy devices and find one of my other controllers to set player 2 back to default controls to use RLBot. I'm using a separate account now for RLBot testing because I don't use the default controls myself.
3. We already force a controller scheme (default), so yeah it would be great if somehow no one had to change their controller schemes to use RLBot. I assume the controls are stored somewhere in `Documents\My Games\Rocket League\TAGame\SaveData\DBE_Production\*.save` so perhaps we could get rocket league to load a different save file (deployed alongside the RLBot dll) when the dll is injected. This would still be a forced controller scheme, but I don't see any reason people would need anything else unless they wanted to move the camera around.

**Comment by drssoccer55** [comment]
Resolved in v3 :)
